# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:12
    container_name: marking_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  marcacion-service:
    build: .
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BROKER: ${KAFKA_BROKER}  # Cambia esto para que apunte al nombre del servicio de Kafka
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: